name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.6
    - run: rustup update stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
